name: Build and Deploy mkdocs to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build-and-deploy:
    name: Build and Deploy mkdocs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest'
          requirements: 'requirements.txt'
          configfile: 'mkdocs.yml'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - name: Discord notification - build and deploy
        if: ${{ success() && github.ref == 'refs/heads/main'}}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "SUCCESS Build and Deploy:\nCommit: ${{ github.event.head_commit.message }}\nRef: ${{ github.ref_name }}\n:tada:"

      - name: Discord notification - build only
        if: ${{ success() && github.ref != 'refs/heads/main'}}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "SUCCESS Build\nCommit: ${{ github.event.head_commit.message }}\nRef: ${{ github.ref_name }}\n:tada:"